[build-system]
requires = ["setuptools>61,<81", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "martini-shaker"
version = "0.1.0"
description = "A Toolkit for the parameterization of physics-based force fields."
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Luís Borges Araújo", email = "luis.borges@ens-lyon.fr"},
  { name = "Pablo Cardona Perez", email = "pablo.cardona_perez@ens-lyon.fr" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "LGPL-2.1-only"
license-files = ["LICENSE"]

dependencies = [
"setuptools>61,<81", 
"ipywidgets==8.1.8",
"numpy",
"matplotlib", 
"scipy",
"mdanalysis",
"tqdm",
"nglview==4.0",
"rdkit"
]

[dependency-groups]
lint = ["ruff==0.16.7", "nbqa", "pre-commit"]
typecheck = ["mypy", "types-tqdm", "scipy-stubs"]
test = ["pytest"]
docs = ["sphinx", "sphinx-design","pydata-sphinx-theme","numpydoc","myst-nb"]
all = [
      { include-group = "lint" },
      { include-group = "typecheck" },
      { include-group = "test" },
      { include-group = "docs" }
      ]


[project.urls]
Homepage = "https://github.com/Martini-Force-Field-Initiative/shaker"
Issues = "https://github.com/Martini-Force-Field-Initiative/shaker/issues"

[tool.ruff]
target-version = "py310"

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["shaker*"]

[tool.setuptools.package-data]
shaker = ["data/**/*"]

# Setuptools deprecated pkg_resources and show a warning about it.
# nglview uses it so we ignore and pin setuptools,81 to make sure it works.
[tool.pytest.ini_options]
filterwarnings = [
  "ignore:pkg_resources is deprecated as an API:UserWarning:nglview",
  "ignore:Deprecated call to `pkg_resources\\.declare_namespace.*:DeprecationWarning",
]

[[tool.mypy.overrides]]
module = [
  "MDAnalysis",
  "MDAnalysis.analysis",
  "MDAnalysis.analysis.distances",
  "nglview"
]
ignore_missing_imports = true
