[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shaker"
version = "0.1.0"
description = "A Toolkit for the parameterization of physics-based force fields."
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Luís Borges Araújo", email = "you@example.com" }]
dependencies = [
  # should probably add the dependencies here hahah
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["shaker*"]

[tool.setuptools.package-data]
shaker = ["data/**/*"]