"""Tests for shaker/itp.py — GROMACS topology file generation."""

import pytest
from shaker.itp import write_initial_CGitp


MAPPING = {
    "MOL": {
        "B1": {"type": "SC3", "charge":  0, "atoms": ["C1", "C2"]},
        "B2": {"type": "TC4", "charge": -1, "atoms": ["C3"]},
        "B3": {"atoms": ["C4"]},          # no type or charge → fallback to defaults
    }
}


@pytest.fixture
def itp_path(tmp_path):
    return tmp_path / "out.itp"


class TestWriteInitialCGItp:
    def test_file_created(self, itp_path):
        write_initial_CGitp("MOL", MAPPING, filename=str(itp_path))
        assert itp_path.exists()

    def test_moleculetype_section(self, itp_path):
        write_initial_CGitp("MOL", MAPPING, filename=str(itp_path))
        content = itp_path.read_text()
        assert "[ moleculetype ]" in content

    def test_resname_in_moleculetype(self, itp_path):
        write_initial_CGitp("MOL", MAPPING, filename=str(itp_path))
        content = itp_path.read_text()
        # resname should appear on the line after [ moleculetype ]
        lines = content.splitlines()
        mol_idx = next(i for i, l in enumerate(lines) if "moleculetype" in l)
        assert "MOL" in lines[mol_idx + 1]

    def test_atoms_section(self, itp_path):
        write_initial_CGitp("MOL", MAPPING, filename=str(itp_path))
        content = itp_path.read_text()
        assert "[ atoms ]" in content

    def test_all_bead_names_present(self, itp_path):
        write_initial_CGitp("MOL", MAPPING, filename=str(itp_path))
        content = itp_path.read_text()
        for name in ("B1", "B2", "B3"):
            assert name in content

    def test_bead_types_written(self, itp_path):
        write_initial_CGitp("MOL", MAPPING, filename=str(itp_path))
        content = itp_path.read_text()
        assert "SC3" in content
        assert "TC4" in content

    def test_missing_type_uses_placeholder(self, itp_path):
        """B3 has no 'type' key — should fall back to 'TYPe'."""
        write_initial_CGitp("MOL", MAPPING, filename=str(itp_path))
        content = itp_path.read_text()
        assert "TYPe" in content

    def test_bead_count(self, itp_path):
        """Three beads → three numbered atom lines."""
        write_initial_CGitp("MOL", MAPPING, filename=str(itp_path))
        lines = itp_path.read_text().splitlines()
        # Atom lines: start with an integer index (strip leading whitespace)
        atom_lines = [l for l in lines if l.strip() and l.strip()[0].isdigit()]
        assert len(atom_lines) == 3

    def test_missing_resname_raises(self, itp_path):
        with pytest.raises(ValueError, match="No mapping found"):
            write_initial_CGitp("XXX", MAPPING, filename=str(itp_path))

    def test_invalid_bead_type_raises(self, itp_path):
        bad_mapping = {"MOL": {"B1": {"type": "ZZZZ", "atoms": ["C1"]}}}
        with pytest.raises(ValueError, match="not a recognized Martini"):
            write_initial_CGitp("MOL", bad_mapping, filename=str(itp_path))

    def test_header_written(self, itp_path):
        write_initial_CGitp("MOL", MAPPING, filename=str(itp_path),
                             header="; generated by test")
        assert "; generated by test" in itp_path.read_text()

    def test_footer_written(self, itp_path):
        write_initial_CGitp("MOL", MAPPING, filename=str(itp_path),
                             footer="; end of file")
        assert "; end of file" in itp_path.read_text()

    def test_header_appears_before_moleculetype(self, itp_path):
        write_initial_CGitp("MOL", MAPPING, filename=str(itp_path),
                             header="; my header")
        content = itp_path.read_text()
        assert content.index("; my header") < content.index("[ moleculetype ]")

    def test_mass_written_when_provided(self, itp_path):
        mapping_with_mass = {
            "MOL": {"B1": {"type": "SC3", "charge": 0, "mass": 54.0, "atoms": ["C1"]}}
        }
        write_initial_CGitp("MOL", mapping_with_mass, filename=str(itp_path))
        assert "54.0" in itp_path.read_text()

    def test_no_mass_line_without_mass_key(self, itp_path):
        """Without 'mass', the atom line should have 7 fields (no mass column)."""
        mapping_no_mass = {
            "MOL": {"B1": {"type": "SC3", "charge": 0, "atoms": ["C1"]}}
        }
        write_initial_CGitp("MOL", mapping_no_mass, filename=str(itp_path))
        lines = itp_path.read_text().splitlines()
        atom_lines = [l for l in lines if l.strip() and l.strip()[0].isdigit()]
        assert len(atom_lines) == 1
        assert len(atom_lines[0].split()) == 7
